# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure Functions: https://aka.ms/python-webapps-actions

name: Build and deploy Python project to Azure Function App - trisonics-scouting-api

on:
  push:
    branches:
      - release
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-function.outputs.webapp-url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies into package
        run: |
          cd trisonics-api
          pip install --target=".python_packages/lib/site-packages" -r requirements.txt

      - name: 'Deploy to Azure Functions'
        uses: Azure/functions-action@v1
        id: deploy-to-function
        with:
          app-name: 'trisonics-scouting-api'
          slot-name: 'Production'
          package: trisonics-api
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_324BBF7DB8764296A9F0839283B8E03D }}
          scm-do-build-during-deployment: false
          enable-oryx-build: false
